{% set name = "pyinstrument" %}
{% set version = "3.4.2" %}
{% set sha256 = "ec79f6fc6f945edd845b1c8b6470de8cb6f65a3cbb3845c533991619ffcb1636" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  entry_points:
    - pyinstrument = pyinstrument.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - nodejs
  run:
    - python
    - pyinstrument_cext >=0.2.2

test:
  imports:
    - pyinstrument
    - pyinstrument.renderers
    - pyinstrument.vendor
  commands:
    - pyinstrument --help

about:
  home: https://github.com/joerick/pyinstrument
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 🚴 Call stack profiler for Python. Shows you why your code is slow!
  dev_url: https://github.com/joerick/pyinstrument
